# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  mailstoreConnector:
    atomicImap:
      protocol: imaps
      host: imap.gmail.com
      port: "993"
      user: atomic.ivyteam@gmail.com
      password: ""
    etherealImap:
      protocol: imaps
      host: imap.ethereal.email
      port: "993"
      user: arnoldo73@ethereal.email
      password: ""
    # Subject pattern used to identify emails for processing. To match by 'contains', use a regular expression like: .*your-pattern.*
    subjectMatches: .*Connector.*
    caseReferenceRegex: \[Ref=(.+?)\]
    # Folder to which the mail will be moved after successful processing
    processedFolderName: Processed
    # Folder to which the mail will be moved if an error occurs
    errorFolderName: ErrorFolder
    # After retrieving an email, the system will create a task assigned to this role.
    retrieveMailTaskRole: Admin
